service: touchscores-api

frameworkVersion: "3"

custom:
  ObjectStorage:
    Ref: ObjectStorage
  DataTable:
    Ref: DataTable

package:
  individually: true
  patterns:
    - "!./**"
    - ./bin/**

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: provided.al2
  architecture: arm64
  region: eu-west-2
  endpointType: REGIONAL
  versionFunctions: false
  memorySize: 128
  timeout: 6
  logs:
    websocket:
      level: ERROR
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [DataTable, Arn]
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - execute-api:Invoke
      Resource: "*"
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - ssm:Describe*
        - ssm:Get*
        - ssm:List*
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - Fn::GetAtt: [ObjectStorage, Arn]

functions:
  entrypoint:
    handler: bootstrap
    package:
      artifact: bin/entrypoint/bootstrap.zip
    environment:
      DB_TBL_NAME: ${self:custom.DataTable}
      OBJECT_STORAGE: ${self:custom.ObjectStorage}
      CORS_ALLOWED_ORIGIN: ${env:CORS_ALLOWED_ORIGIN, "*"}
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
      - http:
          path: update
          method: put
      - http:
          path: get
          method: get
      - schedule:
          method: scheduler
          rate: rate(2 minutes)

resources:
  Resources:
    DataTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-ws-connections-${self:provider.stage}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: TRUE
    ObjectStorage:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: touchscores-api-${self:provider.stage}