name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID }}
      VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull docker images
        run: make docker_pull_images
      - name: Run Go tests
        run: make go_run_test
      - name: Build API image
        run: make build_api
      - name: Deploy API
        run: make deploy_api stage='prod'
      - name: Create env file
        run: make create_env
      - name: Run JS tests
        run: make js_run_unit_tests
      - name: Run JS linting
        run: make js_run_lint
      - name: Build package for FE deployment
        run: make js_run_build
      - name: Deploy FE
        run: make deploy_fe