name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull image
        run: make docker_pull_images
      - name: Run tests
        run: make js_run_unit_tests
      - name: Run linting
        run: make js_run_lint
      - name: Build package for deployment
        run: make js_run_build